openapi: 3.0.0
info:
  title: Device action API
  description: An API for managing device action. For each device actions status store
    inside server database. Set Action for device from GUI, device is responsible
    to reset it after performing action.
  contact:
    name: Alap vyas
    url: smardtv.com
    email: alap.vyas@smardtv.com
  version: 1.0.0

servers:
- url: https://smarthing-cloud-dev.com
  description: Dev Server
- url: https://smarthing-cloud.com
  description: Prod Server

paths:
  /api/devices/v1/action/{deviceId}:
    put:
      summary: update the device action from device.
      parameters:
      - name: deviceId
        in: path
        description: device id of device under question
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: device action is updated.
        400:
          description: Missing/malformed request parameters or body. See error for
            details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: The user is not authenticated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Description of the error.
        request_id:
          type: string
          description: Request ID (same as in X-MEN-RequestID header).
      description: Error descriptor.
      example:
        error: 'failed to decode device group data: JSON payload is empty'
        request_id: f7881e82-0492-49fb-b459-795654e7188a

  responses:
    UnauthorizedError:
      description: Access token in missing or invalid
      
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
